export const EXIF_VALUES_CONSTANTS = {
  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_PER_PAGE: 50,
    MAX_PER_PAGE: 1000,
  },
  DATABASE: {
    COLLECTION_NAME: 'photos',
    EXIF_FIELD_PREFIX: 'exif.',
  },
  VALIDATION: {
    MIN_PROPERTY_NAME_LENGTH: 1,
    MAX_PROPERTY_NAME_LENGTH: 100,
  },
  PERFORMANCE: {
    QUERY_TIMEOUT_MS: 5000,
    MAX_VALUES_THRESHOLD: 100000,
  },
} as const;
